---
:gem:
  :name: "google-cloud-vision-v1"
  :env_prefix: VISION
:defaults:
  :service:
    :default_host: "vision.googleapis.com"
    :oauth_scopes:
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/cloud-vision
